### ISSUE TITLE
Support for quiet mode on wget?

### ISSUE THREAD

**Issue by tonypiazza** [download-maven-plugin/download-maven-plugin#101]
I am using the plugin to download a few large files and am wondering if you would add support for quiet mode to reduce the screen output.

Thanks,

-Tony

**Comment by mickaelistria** [comment]
Sure! Code contributons on this topic would br welcome ;)

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, at Red Hat Developers <https://developers.redhat.com/> community
Elected Committer Representative at the Eclipse Foundation
<https://www.eclipse.org/org/> board of directors

**Comment by tonypiazza** [comment]
I've been looking at the code and wonder if modifying the interactiveMode in settings.xml would resolve this issue.  Thoughts?

**Comment by lchry** [comment]
> I've been looking at the code and wonder if modifying the interactiveMode in settings.xml would resolve this issue. Thoughts?

it looks like this,but I tried to modify my settings profile and  it didn't work.Have you found some elegant ways to solve this problem?

**Comment by longtimeago** [comment]
@tonypiazza does the solution https://github.com/maven-download-plugin/maven-download-plugin/issues/101#issuecomment-452893423 solve your problem?

**Comment by lorenzodallavecchia** [comment]
In my opinion, the interactive mode progress should be displayed by overwriting the last line, like Maven itself does when downloading artifacts. I don't know if that is possible from a MOJO though.

**Comment by lfvjimisola** [comment]
This would be very useful for security purpose when you have to pass a token in URL.

**Comment by longtimeago** [comment]
@tonypiazza `--no-transfer-progress` was added in 1.10.0

treating it as fixed

Thanks everybody involved :)
