### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by hhugu** [download-maven-plugin/download-maven-plugin#110]
I'm trying to access to a private Bitbucket repository to download a file, i set the user name and the password but always is downloading the login page. It seams like the authentication is not running, cause i can download a file from a public repository.

**Comment by amergey** [comment]
I have a similar issue for a service requiring preemptive authentication. Do you know if Bitbucket requires preemptive authentication ? if it is the case I think the issue here is maven-download-plugin is not able to perform preemptive authentication

**Comment by longtimeago** [comment]
@hhugu @amergey preemptive auth is supported since 1.6.9 (`preemptiveAuth` param)

If something is still missing, please, report a new issue with reproduction steps :)
