### ISSUE TITLE
The name of this plugin violates the maven plugin naming convention

### ISSUE THREAD

**Issue by bmarwell** [download-maven-plugin/download-maven-plugin#214]
Hi,

FYI, please consider relocating the plugin to download-maven-plugin.

Rationale: https://maven.apache.org/guides/plugin/guide-java-plugin-development.html#important-notice-plugin-naming-convention-and-apache-maven-trade

> You will typically name your plugin \<yourplugin\>-maven-plugin.
> 
> Calling it maven-\<yourplugin\>-plugin (note "Maven" is at the beginning of the plugin name) is strongly discouraged since it's a reserved naming pattern for official Apache Maven plugins maintained by the Apache Maven team with groupId org.apache.maven.plugins. Using this naming pattern is an infringement of the Apache Maven Trademark.

Guide to relocation:
https://maven.apache.org/guides/mini/guide-relocation.html

**Comment by delanym** [comment]
can close now
