### ISSUE TITLE
Cannot download zip file served by a PHP page.

### ISSUE THREAD

**Issue by LorenzoBettini** [download-maven-plugin/download-maven-plugin#235]
Hi

I'm trying to download a zip file served by the Eclipse download area; this is the URL, which works when used in a browser:

https://www.eclipse.org/downloads/download.php?file=/orion/drops/R-17.0-201801111044/built-codeEdit.zip&mirror_id=1

I configured the plugin as follows:

```xml
<plugin>
	<groupId>com.googlecode.maven-download-plugin</groupId>
	<artifactId>download-maven-plugin</artifactId>
	<version>1.6.8</version>
	<executions>
		<execution>
			<id>install-orion</id>
			<phase>prepare-package</phase>
			<goals>
				<goal>wget</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<url><![CDATA[https://www.eclipse.org/downloads/download.php?file=/orion/drops/R-17.0-201801111044/built-codeEdit.zip&mirror_id=1]]></url>
		<followRedirects>true</followRedirects>
		<outputFileName>built-codeEdit.zip</outputFileName>
		<unpack>true</unpack>
		<outputDirectory>src/main/webapp/orion</outputDirectory>
	</configuration>
</plugin>
```

I'm using `CDATA` to escape the `&` character.

The goal always fails with this error:

```
IO Error: Error while expanding ... /src/main/webapp/orion/built-codeEdit.zip: Archive is not a ZIP archive
```

Because it actually downloads the source of the Eclipse webpage ("download.php").

Am I doing anything wrong in the configuration?

**Comment by vvvvvvch** [comment]
Works fine with 1.7.0 version (mvn -v => 3.9.2)

**Comment by LorenzoBettini** [comment]
Thanks, but I'm not using that anymore: I had to switch to `wagon-maven-plugin` at that time, because of the issue I reported here.
