### ISSUE TITLE
Per #14, plugin was renamed but project was not

### ISSUE THREAD

**Issue by hazendaz** [download-maven-plugin/download-maven-plugin#248]
https://github.com/maven-download-plugin/maven-download-plugin/issues/14

The project should be renamed too.  All forks will get that automatically when it happens from what I recall (been a while...) and there are redirects as well.  Would make sense per the original requirement to go all in.

**Comment by ajarmoniuk** [comment]
Github forks will get that automatically, plugin users will need to change to the new groupId:artifactId by hand, there's no system in place to update changed groupId/artifactId automatically in Maven.

**Comment by hazendaz** [comment]
Correct.  But ground Id and artifact id are currently changed.  Just repo name isn't.  Excluding mention of my other ticket.  So this one just feels like an easy one.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ajarmoniuk** [comment]
Github project name should indeed be changed.

**Comment by ajarmoniuk** [comment]
Guide on how to do that https://maven.apache.org/guides/mini/guide-relocation.html
