### ISSUE TITLE
Consider hosting to github rather than defunct google.code

### ISSUE THREAD

**Issue by hazendaz** [download-maven-plugin/download-maven-plugin#249]
To some, googlecode seems to imply legacy since that was fully archived.  Hosting on github is pretty simple and noted in how to do so in sonatype documentation.  Basically, something like simply changing to 'com.github.maven-download-plugin' would be allowed per project owners here.

Although this is a bit tedious on the maven end if putting up a redirect pom but maybe that was learned in prior #14 adjustments.

**Comment by ajarmoniuk** [comment]
This project is already being hosted on Github.

**Comment by hazendaz** [comment]
Referring to the group id.  Naming there has the impression of where it's hosted.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ajarmoniuk** [comment]
They did change the artifactId in the past. GroupId could also be changed indeed.

**Comment by longtimeago** [comment]
Uff ... I prepared new namespace `io.github.download-maven-plugin` on https://central.sonatype.com/publishing/namespaces to be used as group ID.

But [relocation manual](https://maven.apache.org/guides/mini/guide-relocation.html) is so messy. I just don't understand it :/

**Comment by longtimeago** [comment]
done
