### ISSUE TITLE
401 Unauthorized when executing WGet goal with encrypted password in maven settings.xml

### ISSUE THREAD

**Issue by a-zayati** [download-maven-plugin/download-maven-plugin#264]
Hello,
I upgraded download-maven-plugin to 1.7.1. When I execute WGet goal with encrypted password in maven settings.xml, I get 401 Unauthorized.
Maybe, it is related to this change in [src/main/java/com/googlecode/download/maven/plugin/internal/HttpFileRequester.java](https://github.com/maven-download-plugin/maven-download-plugin/pull/227/files#diff-b3a92a7e6729026e67992bfc8d6f3fd8feb891b73dcffc4149262d689b0abd98).
Regards.

**Comment by longtimeago** [comment]
@a-zayati sorry for the mess. Please, try 1.8.0

**Comment by Playacem** [comment]
I have the same issue with 1.71 and also with 1.8.0. 1.6.8 works correctly woth an encrypted settings.xml password.

**Comment by longtimeago** [comment]
@a-zayati @Playacem @flesser would you mind trying 1.11.5 ? Should fix the issue

**Comment by flesser** [comment]
Yes, 1.11.5 fixes the issue for me, thank you!
